version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travel-backend-app
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
      - PORT=3030
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/travel_backend
      - JWT_SECRET=your-jwt-secret-here-change-in-production
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: travel-backend-postgres
    environment:
      POSTGRES_DB: travel_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
